---
title: "ENVS 193DS Final"
Author: "Stephen Bond"
Data: "2026/06/09"
format: 
  html:
    toc: true # display table of contents
execute:
  message: false # remove messages
  warning: false # remove warnings
---

[GitHub Repo](https://github.com/24Steve24/ENVS-193DS_spring-2026_final)

# Set Up

```{r}
#| label: Read in Packages and Data
#| message: false
#| warning: false

# loading in packages
library(tidyverse) # general use
library(janitor) # cleaning data
library(here) # organizing files
library(rstatix) # statistical relationships
library(MuMIn) # modelling
library(DHARMa) # residual diagnostic simulation
library(ggeffects) # model predictions
library(ggplot2) # visualizations

# read in data
nests <- read_csv(here("data", "nest_data_final.csv")) # read in and make object for nest data
dinner <- read_csv(here("data", "Dinner_Data.csv")) # read in and make object for personal data

```

# Problem 1. Research Writing

## a. Transparent Statistical Methods

In part 1, the researchers used a Generalized Linear Model (GLM) to reach their conclusion and compute that p-value, since the claim answers the central question of how distance to water edge predicts the probability of American Avocet microhabitat use. Additionally, since the variables are binary (use of microhabitat or no use) and continous (distance from water edge) are non-parametric. Furthermore, since the response variable is binary we know the test was a logistic regression, a specific type of generalized linear regression. In part 2, they used a chi-square test because they are examining the relationship between two categorical variables, bird species and habitat type.

## b. Suggestions for rewriting

### Part 1. 
We found that the distance to water edge does act as a predictor for the likelihood American Avocet use microhabitat.

### Part 2.
When looking at the distribution of American Avocet, Forster's Tern, and Black-necked Stilt, we found that there is a relationship between a bird's species and its habitat. This conclusion takes into consideration managed pond, non-tidal marsh, salt pond, tidal marsh, and tidal mudflat as habitats.

